/**
 * Hand-written SEO overrides for blog posts.
 *
 * WHY THIS FILE EXISTS: `content/blogs/_index.json` and the per-slug
 * `.meta.json` files are regenerated by `scripts/extract-blogs.ts` (the
 * `prebuild` step), which reads titles and descriptions straight out of the
 * legacy WordPress HTML. Editing those generated files would be silently
 * reverted on the next build. These overrides are applied at read time in
 * `lib/blog.ts`, so they survive regeneration.
 *
 * WHAT IS OVERRIDDEN: only `<head>` metadata and the `BlogPosting.headline`.
 * The on-page H1 and the blog-card titles still come from the article itself,
 * so the SEO title and the visible headline stay independent — a title tag
 * should not be echoed as the page's heading.
 *
 * RULES APPLIED (see the SEO audit):
 *  - `title` <= 60 characters, primary keyword near the front.
 *  - `description` 150-160 characters, opening with the reader's problem
 *    rather than "Elderly Wellness is a ...", keyword used once, naturally.
 *  - No phone number in the description. The number belongs in the `tel:`
 *    link and the ContactPoint schema, not in the slot that earns the click.
 *  - `ogTitle` / `ogDescription` are written for share context, so they are
 *    deliberately not a copy of the title/description.
 */

export interface BlogSeoOverride {
  /** `<title>` and metadata title. */
  title: string;
  /** `<meta name="description">`. */
  description: string;
  /** og:title / twitter:title. */
  ogTitle: string;
  /** og:description / twitter:description. */
  ogDescription: string;
  /**
   * `BlogPosting.headline` — the article's actual headline, without the
   * "| Elderly Wellness" SEO suffix. Defaults to `title` when omitted.
   */
  headline?: string;
}

export const BLOG_SEO_OVERRIDES: Readonly<
  Record<string, BlogSeoOverride>
> = {
  /* ---------------------------------------------------------------- */
  /* Neighbourhood posts — the phone number used to occupy the opening */
  /* of every one of these descriptions. That was the single most      */
  /* repeated fixable issue on the site.                               */
  /* ---------------------------------------------------------------- */
  "elderly-care-services-in-adyar": {
    title: "Elderly Care Services in Adyar, Chennai | Elderly Wellness",
    description:
      "A parent recovering alone in Adyar needs more than a daily phone call. Elderly Wellness places police-verified nurses and caregivers in homes across Adyar.",
    ogTitle: "Elder Care at Home in Adyar",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Adyar, Chennai.",
    headline: "Elderly Care Services in Adyar, Chennai",
  },
  "elderly-care-services-in-adambakkam": {
    title: "Elderly Care Services in Adambakkam, Chennai",
    description:
      "A parent recovering alone in Adambakkam needs more than a daily phone call. Elderly Wellness sends verified nurses and caregivers to Adambakkam homes.",
    ogTitle: "Elder Care at Home in Adambakkam",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Adambakkam, Chennai.",
    headline: "Elderly Care Services in Adambakkam, Chennai",
  },
  "elderly-care-services-in-alandur": {
    title: "Elderly Care Services in Alandur, Chennai | Elderly Wellness",
    description:
      "A parent recovering alone in Alandur needs more than a daily phone call. Elderly Wellness places police-verified nurses and caregivers in homes across Alandur.",
    ogTitle: "Elder Care at Home in Alandur",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Alandur, Chennai.",
    headline: "Elderly Care Services in Alandur, Chennai",
  },
  "elderly-care-services-in-alapakkam": {
    title: "Elderly Care Services in Alapakkam, Chennai",
    description:
      "A parent living alone in Alapakkam needs more than a phone check-in. Elderly Wellness places police-verified nurses and caregivers in homes across Alapakkam.",
    ogTitle: "Elder Care at Home in Alapakkam",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Alapakkam, Chennai.",
    headline: "Elderly Care Services in Alapakkam, Chennai",
  },
  "elderly-care-services-in-alwarpet": {
    title: "Elderly Care Services in Alwarpet, Chennai",
    description:
      "A parent managing alone in Alwarpet needs more than a daily phone call. Elderly Wellness places police-verified nurses and caregivers in homes across Alwarpet.",
    ogTitle: "Elder Care at Home in Alwarpet",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Alwarpet, Chennai.",
    headline: "Elderly Care Services in Alwarpet, Chennai",
  },
  "elderly-care-services-in-alwarthirunagari": {
    title: "Elderly Care Services in Alwarthirunagari, Chennai",
    description:
      "A parent managing alone in Alwarthirunagari needs more than a daily phone call. Elderly Wellness sends verified nurses and caregivers to Alwarthirunagari homes.",
    ogTitle: "Elder Care at Home in Alwarthirunagari",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Alwarthirunagari.",
    headline: "Elderly Care Services in Alwarthirunagari, Chennai",
  },
  "elderly-care-services-in-ambattur": {
    title: "Elderly Care Services in Ambattur, Chennai",
    description:
      "A parent managing alone in Ambattur needs more than a daily phone call. Elderly Wellness places police-verified nurses and caregivers in homes across Ambattur.",
    ogTitle: "Elder Care at Home in Ambattur",
    ogDescription:
      "Verified nurses, physiotherapists and caregivers for elderly parents in Ambattur, Chennai.",
    headline: "Elderly Care Services in Ambattur, Chennai",
  },
  "elderly-care-services-in-chennai": {
    title: "Elderly Care Services in Chennai | Elderly Wellness",
    description:
      "Arranging care for an ageing parent in Chennai is hard to get right alone. Elderly Wellness places police-verified nurses, physios and caregivers at home.",
    ogTitle: "Elder Care at Home, Across Chennai",
    ogDescription:
      "Nursing, physiotherapy and caregiver support for elderly parents, delivered at home across Chennai.",
    headline: "Elderly Care Services in Chennai",
  },

  /* ---------------------------------------------------------------- */
  /* Editorial posts                                                   */
  /* ---------------------------------------------------------------- */
  "home-care-vs-assisted-living-chennai": {
    title: "Home Care vs Assisted Living in Chennai | Elderly Wellness",
    description:
      "Choosing between home care and assisted living usually comes down to safety versus familiarity. Compare cost, independence and daily support in Chennai.",
    ogTitle: "Home Care or Assisted Living? A Chennai Guide",
    ogDescription:
      "Cost, independence and safety compared, so you can pick the right elder care option for your parent.",
    headline: "Home Care vs Assisted Living in Chennai: Which to Choose",
  },
  "loneliness-mental-wellbeing-elderly-parents": {
    title: "Loneliness in Elderly Parents: Signs to Watch",
    description:
      "Loneliness damages an elderly parent's health as quietly as any illness. Learn the warning signs, and how companionship and caregiver support turn it around.",
    ogTitle: "When a Parent Stops Calling",
    ogDescription:
      "Loneliness harms elderly health as much as physical illness. The signs to watch, and what actually helps.",
    headline: "Loneliness and Mental Wellbeing in Elderly Parents",
  },
  "post-hospital-recovery-care-at-home-chennai": {
    title: "Post-Hospital Recovery Care at Home | Elderly Wellness",
    description:
      "The first fortnight after discharge decides how well an elderly parent recovers. What to arrange before they come home, and how home nursing speeds it up.",
    ogTitle: "The First Two Weeks After Discharge",
    ogDescription:
      "What to arrange before an elderly parent comes home from hospital, and how home nursing shortens recovery.",
    headline: "Post-Hospital Recovery Care at Home in Chennai",
  },
  "early-signs-of-dementia-in-elderly-parents": {
    title: "Early Signs of Dementia in Elderly Parents",
    description:
      "Repeated questions and misplaced keys are easy to excuse as ageing. Learn the early signs of dementia in elderly parents, and when to seek a real assessment.",
    ogTitle: "Is It Ageing, or Is It Dementia?",
    ogDescription:
      "The early signs families miss, and the point at which a parent's forgetfulness needs a proper assessment.",
    headline: "Early Signs of Dementia in Elderly Parents: A Family Guide",
  },
  "fall-prevention-home-safety-checklist-elderly-chennai": {
    title: "Fall Prevention Checklist for Elderly Parents",
    description:
      "One fall at home is often what turns an independent parent into a bedridden one. Work through this room-by-room fall prevention checklist before it happens.",
    ogTitle: "The Fall You Can Still Prevent",
    ogDescription:
      "A room-by-room home safety checklist for elderly parents, from caregivers who see the aftermath.",
    headline: "Fall Prevention and Home Safety Checklist for Elderly Parents in Chennai",
  },
  "exercises-for-seniors-over-75": {
    title: "Safe Exercises for Seniors Over 75 | Elderly Wellness",
    description:
      "Strength fades fastest in the years when a fall costs the most. These safe, simple exercises for seniors over 75 rebuild balance, mobility and confidence.",
    ogTitle: "Exercises That Still Work After 75",
    ogDescription:
      "Simple strength and balance routines that rebuild mobility without putting an older body at risk.",
    headline: "Exercises for Seniors Over 75",
  },
  "how-to-hire-best-caregiver-for-seniors-in-chennai": {
    title: "How to Hire a Caregiver for Seniors in Chennai",
    description:
      "Handing a stranger the keys to your parent's home is the hardest part. A step-by-step guide to hiring a caregiver for seniors in Chennai, with costs and checks.",
    ogTitle: "Hiring Someone You Can Actually Trust",
    ogDescription:
      "Verification, costs, contracts and red flags, so you can hire a caregiver for your parent with confidence.",
    headline: "How to Hire the Best Caregiver for Seniors in Chennai",
  },
  "what-is-the-importance-of-regular-exercising-for-senior-citizens": {
    title: "Why Regular Exercise Matters for Senior Citizens",
    description:
      "Muscle lost after 65 is far harder to rebuild than to keep. Here is why regular exercise matters for senior citizens, and how much is genuinely enough.",
    ogTitle: "Why Movement Matters More After 65",
    ogDescription:
      "The health senior citizens lose to inactivity, and the modest routine that protects strength and balance.",
    headline: "The Importance of Regular Exercise for Senior Citizens",
  },
  "essential-care-regarding-arthritis-for-senior-citizens-to-enhance-their-mobility-and-comfort":
    {
      title: "Arthritis Care for Senior Citizens: Mobility Tips",
      description:
        "Arthritis takes independence gradually, one avoided movement at a time. Practical arthritis care for senior citizens that protects mobility, comfort and sleep.",
      ogTitle: "Keeping Arthritis From Taking Mobility",
      ogDescription:
        "Pain management, movement and home adjustments that keep arthritic joints working for longer.",
      headline:
        "Essential Arthritis Care for Senior Citizens: Mobility and Comfort",
    },
  "necessary-lifestyle-changes-to-prevent-cardiovascular-diseases-for-elderly-citizens":
    {
      title: "Preventing Heart Disease in Elderly Citizens",
      description:
        "Cardiovascular disease kills more elderly people than any other condition, and most of its risk is built from daily habits. The lifestyle changes that matter.",
      ogTitle: "The Habits That Protect an Ageing Heart",
      ogDescription:
        "Diet, movement, sleep and monitoring changes that measurably cut cardiovascular risk in later life.",
      headline:
        "Lifestyle Changes to Prevent Cardiovascular Disease in Elderly Citizens",
    },
  "different-ways-to-prevent-osteoporosis-in-senior-citizens-for-stronger-bone-health":
    {
      title: "How to Prevent Osteoporosis in Senior Citizens",
      description:
        "Osteoporosis is usually silent until a hip breaks. Learn how to prevent osteoporosis in senior citizens through diet, weight-bearing movement and screening.",
      ogTitle: "The Silent Condition Behind Broken Hips",
      ogDescription:
        "Diet, movement and screening choices that keep ageing bones strong enough to survive a fall.",
      headline:
        "Ways to Prevent Osteoporosis in Senior Citizens for Stronger Bones",
    },
  "finding-the-right-balance-between-professional-care-and-family-involvement-for-senior-citizens":
    {
      title: "Balancing Professional and Family Elder Care",
      description:
        "Hiring help does not mean handing your parent over, and doing it all yourself rarely lasts. How families split elder care with professionals without losing it.",
      ogTitle: "Hiring Help Without Stepping Back",
      ogDescription:
        "How families divide elder care with professional caregivers while staying close to the day-to-day.",
      headline:
        "Balancing Professional Care and Family Involvement for Senior Citizens",
    },
  "heres-why-regular-checkups-matter-so-much-for-seniors": {
    title: "Why Regular Health Checkups Matter for Seniors",
    description:
      "Most conditions that disable older people are treatable if caught early enough. Here is why regular checkups matter for seniors, and what to screen for when.",
    ogTitle: "What a Checkup Catches Before You Do",
    ogDescription:
      "The screenings that catch treatable conditions early, and how often an older parent genuinely needs them.",
    headline: "Why Regular Checkups Matter So Much for Seniors",
  },
  "age-related-health-conditions": {
    title: "8 Most Common Age-Related Health Conditions",
    description:
      "Most families meet these conditions one crisis at a time. A plain guide to the eight most common age-related health conditions, their signs and care needs.",
    ogTitle: "The Eight Conditions Most Families Meet",
    ogDescription:
      "Osteoporosis, dementia, diabetes and more: early signs, and the care each one calls for.",
    headline: "8 Most Common Age-Related Health Conditions",
  },
  "nutritious-diets-for-senior-health": {
    title: "Nutritious Diets for Senior Health | Elderly Wellness",
    description:
      "Appetite fades with age long before nutrition needs do. A practical guide to building nutritious diets for senior health, including meals that are easy to eat.",
    ogTitle: "Eating Well When Appetite Fades",
    ogDescription:
      "How to build meals an older parent will actually finish, without losing the nutrition they need.",
    headline: "Nutritious Diets for Senior Health",
  },
  "address-loneliness-and-depression-in-senior-citizens": {
    title: "Loneliness and Depression in Senior Citizens",
    description:
      "Depression in older people is routinely mistaken for ordinary ageing and left untreated. How to recognise loneliness and depression in senior citizens, and act.",
    ogTitle: "Depression Is Not Just Getting Older",
    ogDescription:
      "Why low mood in senior citizens gets dismissed as ageing, and what genuinely helps when it is not.",
    headline: "How to Address Loneliness and Depression in Senior Citizens",
  },
  "home-modifications-for-elder-safety": {
    title: "Home Modifications for Elder Safety | Elderly Wellness",
    description:
      "Most falls happen in rooms a parent has used safely for decades. The home modifications for elder safety that reduce risk most, and where to begin first.",
    ogTitle: "Making a Familiar Home Safe Again",
    ogDescription:
      "The changes that cut fall risk most, room by room, and how to make them without upsetting a parent.",
    headline: "Home Modifications for Elder Safety",
  },
  "personal-hygiene-and-diaper-change-services-for-senior-citizens": {
    title: "Hygiene and Diaper Change Care for Seniors",
    description:
      "Incontinence care is where family caregiving most often breaks down, for both sides. How trained hygiene and diaper change support protects a senior's dignity.",
    ogTitle: "The Care Families Find Hardest",
    ogDescription:
      "How trained hygiene and continence support protects an older parent's dignity, and the family's relationship.",
    headline:
      "Personal Hygiene and Diaper Change Services for Senior Citizens",
  },
  "alzheimers-and-dementia-care-services-for-senior-citizens": {
    title: "Alzheimer's and Dementia Care for Seniors",
    description:
      "Dementia changes what caregiving means, often faster than families can adapt. What specialist Alzheimer's and dementia care for senior citizens actually covers.",
    ogTitle: "Caring for a Parent Who Forgets You",
    ogDescription:
      "What specialist dementia and Alzheimer's care covers, and when families need trained help at home.",
    headline: "Alzheimer's and Dementia Care Services for Senior Citizens",
  },
  "how-proper-meals-and-medication-assistance-improve-senior-health-and-well-being":
    {
      title: "Meal and Medication Support for Seniors",
      description:
        "A missed dose or a skipped meal is how most elderly hospital admissions begin. How meal and medication assistance keeps an older parent stable and independent.",
      ogTitle: "The Two Routines That Prevent Hospital Trips",
      ogDescription:
        "Why meals and medication timing drive elderly health outcomes more than almost anything else at home.",
      headline:
        "How Meals and Medication Assistance Improve Senior Health and Well-Being",
    },
  "activities-of-daily-living-adls-for-parents": {
    title: "Activities of Daily Living (ADLs) Explained",
    description:
      "Bathing, dressing, eating: when a parent starts struggling with these, care needs have changed. What activities of daily living are, and how ADLs guide support.",
    ogTitle: "The Six Tasks That Measure Independence",
    ogDescription:
      "What ADLs are, how they are assessed, and what a parent's score tells you about the help they need.",
    headline:
      "ADLs: What Are Activities of Daily Living, and How Do They Help Your Parents?",
  },
  "what-is-elderly": {
    title: "What Is Elderly? Understanding the Age Group",
    description:
      "The word covers a 60-year-old who still works and a 90-year-old who cannot stand. What elderly actually means, and why the distinction changes the care needed.",
    ogTitle: "Who Counts as Elderly, and Why It Matters",
    ogDescription:
      "The age bands, the definitions behind them, and how each one changes the kind of care a person needs.",
    headline: "What Is Elderly? Understanding the Elderly Age Group",
  },
  "essential-grooming-hygiene-tips-elderly": {
    title: "Grooming and Hygiene Guide for the Elderly",
    description:
      "Grooming is often the first routine to slip, and the first sign a parent needs help. Practical hygiene tips for the elderly that preserve comfort and dignity.",
    ogTitle: "When Grooming Is the First Thing to Slip",
    ogDescription:
      "Practical daily hygiene routines for older adults that protect skin, comfort and self-respect.",
    headline: "Essential Grooming and Hygiene Guide for the Elderly",
  },
  "journey-of-eldery": {
    title: "How Elderly Wellness Started: Our Journey",
    description:
      "Elderly Wellness began with one family unable to find trustworthy care for a parent in Chennai. The story behind the service, and the problem it was built for.",
    ogTitle: "The Family Problem That Started Us",
    ogDescription:
      "Why Elderly Wellness exists: one family's search for care they could trust, and what it turned into.",
    headline: "How It Started: The Inspiring Journey of Elderly Wellness",
  },
  "how-elderly-wellness-works": {
    // Deliberately retargeted away from the brand-process query, which
    // /how-elderly-wellness-works/ (the nav page) owns. This post is the
    // broader "what does home elder care involve" explainer.
    title: "Elderly Care at Home: How It Works",
    description:
      "Most families arranging elder care for the first time do not know what to ask for. A plain walkthrough of how professional elder care at home is set up and run.",
    ogTitle: "Arranging Home Care, Step by Step",
    ogDescription:
      "What professional elderly care at home involves, from the first assessment to day-to-day caregiver visits.",
    headline: "How Elderly Care at Home Works",
  },
  "how-to-increase-sodium-levels-in-elderly-at-home": {
    title: "How to Raise Low Sodium Levels in the Elderly",
    description:
      "Low sodium causes confusion and falls in older adults, and is easily missed. How to safely raise sodium levels in the elderly at home, and when to see a doctor.",
    ogTitle: "The Blood Result Behind Sudden Confusion",
    ogDescription:
      "Why low sodium is dangerous in older adults, how to correct it safely, and the point to seek help.",
    headline:
      "How to Increase Sodium Levels in the Elderly at Home: A Caregiver's Guide",
  },
  "what-is-caregivers": {
    title: "What Is a Caregiver? Duties and Responsibilities",
    description:
      "Families often hire a caregiver without knowing what the role should include. What a caregiver does, the duties to expect, and how they differ from a nurse.",
    ogTitle: "What a Caregiver Actually Does",
    ogDescription:
      "The duties, boundaries and skills of a professional caregiver, and how the role differs from nursing.",
    headline: "What Is a Caregiver? Duties, Responsibilities and Benefits",
  },
  "home-modifications-for-seniors": {
    // Differentiated from /blogs/home-modifications-for-elder-safety/:
    // this one is the numbered checklist, that one is the risk explainer.
    title: "16 Home Modifications for Senior Safety",
    description:
      "Small changes to a familiar house are what keep an ageing parent independent in it. Sixteen home modifications for seniors, ranked by the risk each one removes.",
    ogTitle: "16 Changes That Keep a Parent Independent",
    ogDescription:
      "Grab rails to lighting: sixteen home modifications for seniors, ordered by the risk each one removes.",
    headline: "16 Home Modifications for Seniors to Enhance Safety and Comfort",
  },
};
